let movies = []
function GenerateID() { }
function createMovie() { }
function renderMovie() { }
function updateStatistics() { }
function handleAddMovie() { }
function setupFormListener() { }
function handleMovieClick() { }
function setupMovieListListeners() { }
function enableMovieEditing() { }
function finishMovieEditing() { }
function handleEditKey() { }
function setupEditListeners() { }
function handleSearch() { }
function setupSearchListener() { }
function sortMoviesBy() { }
function setupSortButtons() { }
function filterMoviesBy() { }
function setupFilterButtons() { }
function announce() { }
function bootSystem() { }
document.addEventListener("DOMContentLoaded", bootSystem);